version: '3'
services:
  todofront:
    build: ./todo-app/front-end
    ports:
      - "3000:3000"
    depends_on:
      - todoback
  todoback:
    build: ./todo-app/back-end
    ports:
      - "3001:3001"
    depends_on:
      - todofront
      - todoback
    environment:
      - FRONT_HOST=todofront
  todotest:
    build: ./todo-app/tests
